platform :ios, '7.0'
pod 'MJExtension'
pod 'SDWebImage', '~> 3.7.3'
pod 'AFNetworking', '~> 2.4.1'
pod 'FMDB', '~> 2.4'
pod 'Toast', '~> 2.4'
pod 'XHRealTimeBlur'
pod 'pop'
pod 'ZXingObjC', '~> 3.0'
pod 'LBXScan'
pod 'ActionSheetPicker-3.0', '~> 2.0.4'
pod 'BmobSDK'
pod 'BlurView', '~> 1.1'
pod 'NJKWebViewProgress'
pod 'AMapLocation'
pod 'AMap3DMap'

